### ISSUE TITLE
oath token issue , continue

### ISSUE THREAD

**Issue by compadvance** [michabbb/php-ebay-sdk#3]
Hi Mate , 
I didnt realised you not receiving my direct email , my apologies , 
The problem is still there ,
answering you question why not to use trading API :  GetItem returns only 1 url for gallery pics while I am trying to get whole gallery urls.
 Please see bellow my laetst call for GetSingleItem
object(macropage\ebaysdk\shopping\ServiceType\Service)#57 (4) {
  ["soapClient":"WsdlToPhp\PackageBase\AbstractSoapClientBase":private]=>
  object(SoapClient)#82 (13) {
    ["trace"]=>
    int(1)
    ["_classmap"]=>
    array(63) {
      ["AbstractRequestType"]=>
      string(58) "\macropage\ebaysdk\shopping\StructType\AbstractRequestType"
      ["AbstractResponseType"]=>
      string(59) "\macropage\ebaysdk\shopping\StructType\AbstractResponseType"
      ["AmountType"]=>
      string(49) "\macropage\ebaysdk\shopping\StructType\AmountType"
      ["ErrorParameterType"]=>
      string(57) "\macropage\ebaysdk\shopping\StructType\ErrorParameterType"
      ["ErrorType"]=>
      string(48) "\macropage\ebaysdk\shopping\StructType\ErrorType"
      ["SimpleUserType"]=>
      string(53) "\macropage\ebaysdk\shopping\StructType\SimpleUserType"
      ["AddressType"]=>
      string(50) "\macropage\ebaysdk\shopping\StructType\AddressType"
      ["AverageRatingDetailsType"]=>
      string(63) "\macropage\ebaysdk\shopping\StructType\AverageRatingDetailsType"
      ["BusinessSellerDetailsType"]=>
      string(64) "\macropage\ebaysdk\shopping\StructType\BusinessSellerDetailsType"
      ["BuyingGuideDetailsType"]=>
      string(61) "\macropage\ebaysdk\shopping\StructType\BuyingGuideDetailsType"
      ["BuyingGuideType"]=>
      string(54) "\macropage\ebaysdk\shopping\StructType\BuyingGuideType"
      ["CatalogProductType"]=>
      string(57) "\macropage\ebaysdk\shopping\StructType\CatalogProductType"
      ["CategoryArrayType"]=>
      string(55) "\macropage\ebaysdk\shopping\ArrayType\CategoryArrayType"
      ["CategoryType"]=>
      string(51) "\macropage\ebaysdk\shopping\StructType\CategoryType"
      ["CharityType"]=>
      string(50) "\macropage\ebaysdk\shopping\StructType\CharityType"
      ["DiscountPriceInfoType"]=>
      string(60) "\macropage\ebaysdk\shopping\StructType\DiscountPriceInfoType"
      ["DistanceType"]=>
      string(51) "\macropage\ebaysdk\shopping\StructType\DistanceType"
      ["DomainHistogramType"]=>
      string(58) "\macropage\ebaysdk\shopping\StructType\DomainHistogramType"
      ["ExternalProductIDType"]=>
      string(60) "\macropage\ebaysdk\shopping\StructType\ExternalProductIDType"
      ["FeedbackDetailType"]=>
      string(57) "\macropage\ebaysdk\shopping\StructType\FeedbackDetailType"
      ["FeedbackHistoryType"]=>
      string(58) "\macropage\ebaysdk\shopping\StructType\FeedbackHistoryType"
      ["FeedbackPeriodType"]=>
      string(57) "\macropage\ebaysdk\shopping\StructType\FeedbackPeriodType"
      ["FindProductsRequestType"]=>
      string(62) "\macropage\ebaysdk\shopping\StructType\FindProductsRequestType"
      ["FindProductsResponseType"]=>
      string(63) "\macropage\ebaysdk\shopping\StructType\FindProductsResponseType"
      ["GetCategoryInfoRequestType"]=>
      string(65) "\macropage\ebaysdk\shopping\StructType\GetCategoryInfoRequestType"
      ["GetCategoryInfoResponseType"]=>
      string(66) "\macropage\ebaysdk\shopping\StructType\GetCategoryInfoResponseType"
      ["GetItemStatusRequestType"]=>
      string(63) "\macropage\ebaysdk\shopping\StructType\GetItemStatusRequestType"
      ["GetItemStatusResponseType"]=>
      string(64) "\macropage\ebaysdk\shopping\StructType\GetItemStatusResponseType"
      ["GetMultipleItemsRequestType"]=>
      string(66) "\macropage\ebaysdk\shopping\StructType\GetMultipleItemsRequestType"
      ["GetMultipleItemsResponseType"]=>
      string(67) "\macropage\ebaysdk\shopping\StructType\GetMultipleItemsResponseType"
      ["GetShippingCostsRequestType"]=>
      string(66) "\macropage\ebaysdk\shopping\StructType\GetShippingCostsRequestType"
      ["GetShippingCostsResponseType"]=>
      string(67) "\macropage\ebaysdk\shopping\StructType\GetShippingCostsResponseType"
      ["GetSingleItemRequestType"]=>
      string(63) "\macropage\ebaysdk\shopping\StructType\GetSingleItemRequestType"
      ["GetSingleItemResponseType"]=>
      string(64) "\macropage\ebaysdk\shopping\StructType\GetSingleItemResponseType"
      ["GetUserProfileRequestType"]=>
      string(64) "\macropage\ebaysdk\shopping\StructType\GetUserProfileRequestType"
      ["GetUserProfileResponseType"]=>
      string(65) "\macropage\ebaysdk\shopping\StructType\GetUserProfileResponseType"
      ["GeteBayTimeRequestType"]=>
      string(61) "\macropage\ebaysdk\shopping\StructType\GeteBayTimeRequestType"
      ["GeteBayTimeResponseType"]=>
      string(62) "\macropage\ebaysdk\shopping\StructType\GeteBayTimeResponseType"
      ["HistogramEntryType"]=>
      string(57) "\macropage\ebaysdk\shopping\StructType\HistogramEntryType"
      ["InternationalShippingServiceOptionType"]=>
      string(77) "\macropage\ebaysdk\shopping\StructType\InternationalShippingServiceOptionType"
      ["ItemCompatibilityListType"]=>
      string(64) "\macropage\ebaysdk\shopping\StructType\ItemCompatibilityListType"
      ["ItemCompatibilityType"]=>
      string(60) "\macropage\ebaysdk\shopping\StructType\ItemCompatibilityType"
      ["NameValueListArrayType"]=>
      string(60) "\macropage\ebaysdk\shopping\ArrayType\NameValueListArrayType"
      ["NameValueListType"]=>
      string(56) "\macropage\ebaysdk\shopping\StructType\NameValueListType"
      ["PickUpInStoreDetailsType"]=>
      string(63) "\macropage\ebaysdk\shopping\StructType\PickUpInStoreDetailsType"
      ["PicturesType"]=>
      string(51) "\macropage\ebaysdk\shopping\StructType\PicturesType"
      ["ProductIDType"]=>
      string(52) "\macropage\ebaysdk\shopping\StructType\ProductIDType"
      ["QuantityInfo"]=>
      string(51) "\macropage\ebaysdk\shopping\StructType\QuantityInfo"
      ["ReturnPolicyType"]=>
      string(55) "\macropage\ebaysdk\shopping\StructType\ReturnPolicyType"
      ["SalesTaxType"]=>
      string(51) "\macropage\ebaysdk\shopping\StructType\SalesTaxType"
      ["SellingStatusType"]=>
      string(56) "\macropage\ebaysdk\shopping\StructType\SellingStatusType"
      ["ShippingCostSummaryType"]=>
      string(62) "\macropage\ebaysdk\shopping\StructType\ShippingCostSummaryType"
      ["ShippingDetailsType"]=>
      string(58) "\macropage\ebaysdk\shopping\StructType\ShippingDetailsType"
      ["ShippingServiceOptionType"]=>
      string(64) "\macropage\ebaysdk\shopping\StructType\ShippingServiceOptionType"
      ["SimpleItemType"]=>
      string(53) "\macropage\ebaysdk\shopping\StructType\SimpleItemType"
      ["StorefrontType"]=>
      string(53) "\macropage\ebaysdk\shopping\StructType\StorefrontType"
      ["TaxJurisdictionType"]=>
      string(58) "\macropage\ebaysdk\shopping\StructType\TaxJurisdictionType"
      ["TaxTableType"]=>
      string(51) "\macropage\ebaysdk\shopping\StructType\TaxTableType"
      ["UnitInfoType"]=>
      string(51) "\macropage\ebaysdk\shopping\StructType\UnitInfoType"
      ["VATDetailsType"]=>
      string(53) "\macropage\ebaysdk\shopping\StructType\VATDetailsType"
      ["VariationSpecificPictureSetType"]=>
      string(70) "\macropage\ebaysdk\shopping\StructType\VariationSpecificPictureSetType"
      ["VariationType"]=>
      string(52) "\macropage\ebaysdk\shopping\StructType\VariationType"
      ["VariationsType"]=>
      string(53) "\macropage\ebaysdk\shopping\StructType\VariationsType"
    }
    ["_features"]=>
    int(5)
    ["_stream_context"]=>
    resource(38) of type (stream-context)
    ["_soap_version"]=>
    int(1)
    ["sdl"]=>
    resource(40) of type (SOAP SDL)
    ["__last_request"]=>
    string(365) "<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:ebay:apis:eBLBaseComponents"><SOAP-ENV:Header/><SOAP-ENV:Body><ns1:GetSingleItemRequest><ns1:ItemID>334664496876</ns1:ItemID><ns1:VariationSKU>Details</ns1:VariationSKU></ns1:GetSingleItemRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>
"
    ["httpsocket"]=>
    resource(41) of type (stream)
    ["_use_proxy"]=>
    int(0)
    ["httpurl"]=>
    resource(42) of type (SOAP URL)
    ["__last_request_headers"]=>
    string(2184) "POST /shopping HTTP/1.1
Host: open.api.ebay.com
Connection: Keep-Alive
User-Agent: PHP-SOAP/7.4.33
Content-Type: text/xml; charset=utf-8
SOAPAction: ""
Content-Length: 365
X-EBAY-SOA-OPERATION-NAME: GetSingleItem
X-EBAY-API-IAF-TOKEN: ########################## token here correct #########################################
X-EBAY-SOA-GLOBAL-ID: 3

"
    ["__last_response_headers"]=>
    string(180) "HTTP/1.1 404 Not Found
date: Thu, 26 Jan 2023 16:29:46 GMT
server: ebay-proxy-server
content-length: 0
x-envoy-upstream-service-time: 12
x-ebay-pop-id: UFES2-RNOAZ03-openapi
"
    ["__soap_fault"]=>
    object(SoapFault)#124 (9) {
      ["message":protected]=>
      string(9) "Not Found"
      ["string":"Exception":private]=>
      string(0) ""
      ["code":protected]=>
      int(0)
      ["file":protected]=>
      string(99) "/var/www/erp/public/compadvance_erp/EbayAPIs/php-ebay-sdk-php7/src_shopping/ServiceType/Service.php"
      ["line":protected]=>
      int(139)
      ["trace":"Exception":private]=>
      array(13) {
        [0]=>
        array(3) {
          ["function"]=>
          string(11) "__doRequest"
          ["class"]=>
          string(10) "SoapClient"
          ["type"]=>
          string(2) "->"
        }
        [1]=>
        array(5) {
          ["file"]=>
          string(99) "/var/www/erp/public/compadvance_erp/EbayAPIs/php-ebay-sdk-php7/src_shopping/ServiceType/Service.php"
          ["line"]=>
          int(139)
          ["function"]=>
          string(10) "__soapCall"
          ["class"]=>
          string(10) "SoapClient"
          ["type"]=>
          string(2) "->"
        }
        [2]=>
        array(3) {
          ["function"]=>
          string(13) "GetSingleItem"
          ["class"]=>
          string(46) "macropage\ebaysdk\shopping\ServiceType\Service"
          ["type"]=>
          string(2) "->"
        }
        [3]=>
        array(3) {
          ["file"]=>
          string(71) "/var/www/erp/public/compadvance_erp/EbayAPIs/php-ebay-sdk-php7/base.php"
          ["line"]=>
          int(142)
          ["function"]=>
          string(20) "call_user_func_array"
        }
        [4]=>
        array(5) {
          ["file"]=>
          string(75) "/var/www/erp/public/compadvance_erp/EbayAPIs/php-ebay-sdk-php7/shopping.php"
          ["line"]=>
          int(66)
          ["function"]=>
          string(4) "call"
          ["class"]=>
          string(27) "macropage\ebaysdk\base\base"
          ["type"]=>
          string(2) "->"
        }
        [5]=>
        array(5) {
          ["file"]=>
          string(54) "/var/www/erp/public/compadvance_erp/models/ebaySdk.php"
          ["line"]=>
          int(60)
          ["function"]=>
          string(6) "__call"
          ["class"]=>
          string(35) "macropage\ebaysdk\shopping\shopping"
          ["type"]=>
          string(2) "->"
        }
        [6]=>
        array(5) {
          ["file"]=>
          string(66) "/var/www/erp/public/compadvance_erp/controllers/ebayController.php"
          ["line"]=>
          int(3329)
          ["function"]=>
          string(7) "request"
          ["class"]=>
          string(12) "ebaySdkModel"
          ["type"]=>
          string(2) "->"
        }
        [7]=>
        array(5) {
          ["file"]=>
          string(77) "/var/www/erp/public/compadvance_erp/controllers/Abstract/SecureController.php"
          ["line"]=>
          int(33)
          ["function"]=>
          string(25) "recover_gallery_from_ebay"
          ["class"]=>
          string(14) "ebayController"
          ["type"]=>
          string(2) "->"
        }
        
      }
      ["previous":"Exception":private]=>
      NULL
      ["faultstring"]=>
      string(9) "Not Found"
      ["faultcode"]=>
      string(4) "HTTP"
    }
  }
  ["result":"WsdlToPhp\PackageBase\AbstractSoapClientBase":private]=>
  NULL
  ["lastError":"WsdlToPhp\PackageBase\AbstractSoapClientBase":private]=>
  array(1) {
    ["macropage\ebaysdk\shopping\ServiceType\Service::GetSingleItem"]=>
    object(SoapFault)#124 (9) {
      ["message":protected]=>
      string(9) "Not Found"
      ["string":"Exception":private]=>
      string(0) ""
      ["code":protected]=>
      int(0)
      ["file":protected]=>
      string(99) "/var/www/erp/public/compadvance_erp/EbayAPIs/php-ebay-sdk-php7/src_shopping/ServiceType/Service.php"
      ["line":protected]=>
      int(139)
      ["trace":"Exception":private]=>
      array(13) {
        [0]=>
        array(3) {
          ["function"]=>
          string(11) "__doRequest"
          ["class"]=>
          string(10) "SoapClient"
          ["type"]=>
          string(2) "->"
        }
        [1]=>
        array(5) {
          ["file"]=>
          string(99) "/var/www/erp/public/compadvance_erp/EbayAPIs/php-ebay-sdk-php7/src_shopping/ServiceType/Service.php"
          ["line"]=>
          int(139)
          ["function"]=>
          string(10) "__soapCall"
          ["class"]=>
          string(10) "SoapClient"
          ["type"]=>
          string(2) "->"
        }
        [2]=>
        array(3) {
          ["function"]=>
          string(13) "GetSingleItem"
          ["class"]=>
          string(46) "macropage\ebaysdk\shopping\ServiceType\Service"
          ["type"]=>
          string(2) "->"
        }
        [3]=>
        array(3) {
          ["file"]=>
          string(71) "/var/www/erp/public/compadvance_erp/EbayAPIs/php-ebay-sdk-php7/base.php"
          ["line"]=>
          int(142)
          ["function"]=>
          string(20) "call_user_func_array"
        }
        [4]=>
        array(5) {
          ["file"]=>
          string(75) "/var/www/erp/public/compadvance_erp/EbayAPIs/php-ebay-sdk-php7/shopping.php"
          ["line"]=>
          int(66)
          ["function"]=>
          string(4) "call"
          ["class"]=>
          string(27) "macropage\ebaysdk\base\base"
          ["type"]=>
          string(2) "->"
        }
        [5]=>
        array(5) {
          ["file"]=>
          string(54) "/var/www/erp/public/compadvance_erp/models/ebaySdk.php"
          ["line"]=>
          int(60)
          ["function"]=>
          string(6) "__call"
          ["class"]=>
          string(35) "macropage\ebaysdk\shopping\shopping"
          ["type"]=>
          string(2) "->"
        }

      }
      ["previous":"Exception":private]=>
      NULL
      ["faultstring"]=>
      string(9) "Not Found"
      ["faultcode"]=>
      string(4) "HTTP"
    }
  }
  ["outputHeaders":protected]=>
  array(0) {
  }
}

**Comment by michabbb** [comment]
sorry, didn´t see any email. but this is terrible to read. please show me only your RAW XML-Request you are sending.
you cat get that by setting up a logger and than use this method to get everything:

https://github.com/michabbb/php-ebay-sdk/blob/6bed0ea37aa3d7ae0fb1dbd0567305c776fef5a5/base.php#L179

**Comment by compadvance** [comment]
I went thorugh the log above to find out that ns1:VariationSKUDetails</ns1:VariationSKU> caused the  problem 
all works now , thanks for your help again

**Comment by michabbb** [comment]
that´s what i thought because that´s what ebay said in its error message 😏 
would be nice if you could provide your code changes (snippet) that show how you modified the code to make it work with the oauth token. thanks ;)

**Comment by compadvance** [comment]
Hi , in order to get this code working with oauth , I added following code to base.php starting form line 130 approx where SHopping headers being set, just keep in mind that in this scenario under $appid is our oAuth token . Hope this helps : 
          
  case 'macropage\ebaysdk\shopping\ServiceType\Service':    // Shopping
                if (method_exists($this->Service, $method)) {

                    $this->Service->setHttpHeader('X-EBAY-SOA-OPERATION-NAME', $method);
                    if ($this->siteId) {
                        $this->Service->setHttpHeader('X-EBAY-API-IAF-TOKEN', $this->appid);
                        $this->Service->setHttpHeader('X-EBAY-SOA-GLOBAL-ID', $this->siteId);
                    }

                    $this->Service->setLocation($this->api_endpoint . '?callname=' . $method . '&siteid=' . $this->siteId . '&version=' . $this->version . '&routing=new');

                    $result = call_user_func_array(
                            [
                                $this->Service,
                                $method
                            ], $args);

                    $this->log($method);

                    return $result;
                }

**Comment by michabbb** [comment]
as soon i find some free minutes, i will add this to branch `php8`, thanks.
